# Generated by Django 5.2.6 on 2026-01-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
