# Generated by Django 5.2.6 on 2026-01-05 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_spouse_id_member_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent member (usually father or mother) for hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='members.member'),
        ),
    ]
