# Generated by Django 5.2.6 on 2026-01-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='relation',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('spouse', 'Spouse'), ('father', 'Father'), ('mother', 'Mother'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('brother', 'Brother'), ('sister', 'Sister'), ('son', 'Son'), ('daughter', 'Daughter'), ('uncle', 'Uncle'), ('bua', 'Bua'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
