# Generated by Django 5.2.6 on 2026-01-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/member/'),
        ),
    ]
