# Generated by Django 6.0 on 2026-08-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='parent',
        ),
        migrations.AddField(
            model_name='member',
            name='father',
            field=models.ForeignKey(blank=True, help_text='Father of the member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='members.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='mother',
            field=models.ForeignKey(blank=True, help_text='Mother of the member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='members.member'),
        ),
        migrations.CreateModel(
            name='RelationshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_relation', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('father', 'Father'), ('mother', 'Mother'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('brother', 'Brother'), ('sister', 'Sister'), ('son', 'Son'), ('daughter', 'Daughter'), ('uncle', 'Uncle'), ('bua', 'Bua'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_relationship_requests', to='members.member')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_relationship_requests', to='members.member')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sender', 'receiver', 'status'), name='unique_pending_request_between_members')],
            },
        ),
    ]
